name: CI Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'terraform/**'
    workflow_dispatch:

defaults:
  run:
    working-directory: terraform

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        uses: terraform fmt -check -recursive

      - name: Terraform Init
        uses: terraform init

      - name: Terraform Validate
        uses: terraform validate

      - name: Terraform Plan
        uses: terraform plan -input+false

      - name: Terraform Apply
        uses: terraform apply    
